//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pool_Counters_v2._0.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point mainLocation {
            get {
                return ((global::System.Drawing.Point)(this["mainLocation"]));
            }
            set {
                this["mainLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string lastChamp {
            get {
                return ((string)(this["lastChamp"]));
            }
            set {
                this["lastChamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int champsCount {
            get {
                return ((int)(this["champsCount"]));
            }
            set {
                this["champsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string counters {
            get {
                return ((string)(this["counters"]));
            }
            set {
                this["counters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25, 25, 25")]
        public global::System.Drawing.Color firstGradientColor {
            get {
                return ((global::System.Drawing.Color)(this["firstGradientColor"]));
            }
            set {
                this["firstGradientColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12, 12, 12")]
        public global::System.Drawing.Color secGradientColor {
            get {
                return ((global::System.Drawing.Color)(this["secGradientColor"]));
            }
            set {
                this["secGradientColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Horizontal")]
        public global::System.Drawing.Drawing2D.LinearGradientMode gradientMode {
            get {
                return ((global::System.Drawing.Drawing2D.LinearGradientMode)(this["gradientMode"]));
            }
            set {
                this["gradientMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string playerRoleSolo {
            get {
                return ((string)(this["playerRoleSolo"]));
            }
            set {
                this["playerRoleSolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string playerRoleFlex {
            get {
                return ((string)(this["playerRoleFlex"]));
            }
            set {
                this["playerRoleFlex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\"Teemo\",\"Teemo\",\"Teemo\",\"Teemo\",\"Teemo\",\"Teemo\"]")]
        public string poolSolo {
            get {
                return ((string)(this["poolSolo"]));
            }
            set {
                this["poolSolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\"Teemo\",\"Teemo\",\"Teemo\",\"Teemo\",\"Teemo\",\"Teemo\"]")]
        public string poolFlex {
            get {
                return ((string)(this["poolFlex"]));
            }
            set {
                this["poolFlex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Your nickname here")]
        public string playerNickname {
            get {
                return ((string)(this["playerNickname"]));
            }
            set {
                this["playerNickname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TeemoDacy")]
        public string playerRealNickname {
            get {
                return ((string)(this["playerRealNickname"]));
            }
            set {
                this["playerRealNickname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastPageUsed {
            get {
                return ((string)(this["lastPageUsed"]));
            }
            set {
                this["lastPageUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int rolePadding {
            get {
                return ((int)(this["rolePadding"]));
            }
            set {
                this["rolePadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool applyToAllGradients {
            get {
                return ((bool)(this["applyToAllGradients"]));
            }
            set {
                this["applyToAllGradients"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool draftMusic {
            get {
                return ((bool)(this["draftMusic"]));
            }
            set {
                this["draftMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultSpells {
            get {
                return ((string)(this["defaultSpells"]));
            }
            set {
                this["defaultSpells"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showTimeInSeconds {
            get {
                return ((bool)(this["showTimeInSeconds"]));
            }
            set {
                this["showTimeInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool editSpellsMode {
            get {
                return ((bool)(this["editSpellsMode"]));
            }
            set {
                this["editSpellsMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string spellsRoles {
            get {
                return ((string)(this["spellsRoles"]));
            }
            set {
                this["spellsRoles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoStartSpells {
            get {
                return ((bool)(this["autoStartSpells"]));
            }
            set {
                this["autoStartSpells"] = value;
            }
        }
    }
}
